### ISSUE TITLE
Rename "SoundShit" -> ???

### ISSUE THREAD

**Issue by sylv256** [hYdos/Lint#49]
Rename "SoundShit" to something more descriptive. I know I'm nitpicking at this point, but it's not helpful to someone trying to read your code 😆

**Comment by valoeghese** [comment]
ok maybe

**Comment by valoeghese** [comment]
later

**Comment by sylv256** [comment]
Also, you should probably rename some of the methods/fields inside of the class. "`doShit`" says nothing about the code. 😕

**Comment by valoeghese** [comment]
I did this
