### ISSUE TITLE
Unregisted stuff

### ISSUE THREAD

**Issue by K0-RR** [hYdos/Lint#53]
According to Blame:
lint:sicieron_ore
lint:tarscan_ore

**Comment by hYdos** [comment]
Blame? those 2 are registered

**Comment by K0-RR** [comment]
https://www.curseforge.com/minecraft/mc-mods/blame-fabric

**Comment by hYdos** [comment]
that mod is broken. i have checked and the register methods are been called. please report this to them.

**Comment by K0-RR** [comment]
Ok, I will report this to them.

**Comment by TelepathicGrunt** [comment]
@hYdos No actually, Blame is right. 

https://github.com/hYdos/Lint/blob/cd227cca539d54047d35678dcf4ce63b2605d0f2/src/main/java/me/hydos/lint/world/feature/Features.java#L77-L90

The parenthesis for the register here needs to be on the very end. For example, for TARSCAN_ORE, you registered the configuredfeature 
`Feature.ORE.configure(new OreFeatureConfig(FUNNI_STONE, LintBlocks.TARSCAN_ORE.getDefaultState(), 9)).rangeOf(64)`. 
But you add two more decorators on the end and actually is adding a brand new configuredfeature that is
 `Feature.ORE.configure(new OreFeatureConfig(FUNNI_STONE, LintBlocks.TARSCAN_ORE.getDefaultState(), 9)).rangeOf(64).spreadHorizontally().repeat(20)` 
 which is not registered.

Every time you call a decorator, it actually wraps the previous configuredfeature in a brand new one and that final one is the one that needs to be registered before added to biomes. You cant register the inner configuredfeature as the biome codec will not recognize the outside final form and switch to object mode before blowing up other people's registered configuredfeatured from the biome.

I hope this helps

**Comment by hYdos** [comment]
@valoeghese

**Comment by valoeghese** [comment]
So hydos want to be reminded who wrote that code?

**Comment by hYdos** [comment]
yeef

**Comment by Neubulae** [comment]
hi

**Comment by hYdos** [comment]
fixed
