### ISSUE TITLE
Minecraft doesn't add Fraiya dimension to the level data after the world has generated

### ISSUE THREAD

**Issue by panaretos** [hYdos/Lint#62]

**Comment by valoeghese** [comment]
What other mods do you have installed?

**Comment by valoeghese** [comment]
And are you sure it's not just lag? Sometimes it can take a few seconds to teleport

**Comment by panaretos** [comment]
we have about 65 mods.   the server has been running pretty lag free since we started it a couple months ago.  
it works in single player,  but not on MP server

**Comment by valoeghese** [comment]
Does the server work in multiplayer when only the mod is installed?

I'll test it when I have time and see what the issue is

**Comment by valoeghese** [comment]
I'm testing this now

**Comment by valoeghese** [comment]
It works on my end @panaretos

**Comment by hYdos** [comment]
its a bug with dfu. will be fixed soon tm

**Comment by valoeghese** [comment]
I tested a second time and it works on my end again. It might be a DFU bug, in which case regenerating the dimension might be the best course idk. Or wait for us to figure out how to use dfu's api.

**Comment by hYdos** [comment]
irr

**Comment by valoeghese** [comment]
If this is still an issue don't close it

**Comment by hYdos** [comment]
:tiny

**Comment by TelepathicGrunt** [comment]
suggestion, make the dimension be a worldgen json file instead. And then use this mixin to feed the real world seed to the biome source/chunk generator.

https://github.com/TelepathicGrunt/WorldBlender-Fabric/blob/35e2237f7657487b8c38ae649f79d5e7a513397e/src/main/java/com/telepathicgrunt/worldblender/mixin/dimensions/GeneratorOptionsMixin.java#L24

Worldgen json files makes it easier to create dimensions as minecraft will just work(tm) and make it for you

**Comment by valoeghese** [comment]
Hydos, we must use ARRp to anti-json this json

**Comment by valoeghese** [comment]
plsfix

**Comment by valoeghese** [comment]
working on this now

**Comment by valoeghese** [comment]
probably fixed

**Comment by valoeghese** [comment]
thanks tele
