### ISSUE TITLE
Still overcast on fraiya sometimes

### ISSUE THREAD

**Issue by valoeghese** [hYdos/Lint#64]
![image](https://user-images.githubusercontent.com/46117728/111893921-53faa100-8a6b-11eb-83de-afe5ead342dc.png)

(this is rain but not rain. it interferes with our based rendering smh)

**Comment by valoeghese** [comment]
I bet we left the code for this in lint sky somewhere. If not, maybe a few more mixins are needed to set the weather to clear here if it ever goes overcast lol. Or to just prevent weather changes and only allow sunny. 

When we do weather we can probably do it later. When we can get weather commands actually touching Fraiya properly.

**Comment by valoeghese** [comment]
![image](https://user-images.githubusercontent.com/46117728/111893985-d2574300-8a6b-11eb-8109-2bfaa13c91b3.png)
lol rejoining t he world does something

**Comment by valoeghese** [comment]
this behaviour is cursed

**Comment by valoeghese** [comment]
Probably due to time set messing with weather and our code not intercepting it

**Comment by sylv256** [comment]
i've never experienced this. can you provide a way to reproduce it?

**Comment by valoeghese** [comment]
If this is still a problem I don't care and idk
